name: ODW Common component CI

# CI pipeline for common ODW components
parameters:
# User-specified environment to deploy to
- name: env
  default: 'test'
  values:
  - 'build'
  - 'dev'
  - 'test'
  - 'prod'

# Run when Pull Request raised to the main branch
pr:
- main

# Run when merged into main
trigger:
 branches:
  include:
  - main

variables:

- name: variableGroupName
  ${{ if eq(parameters.env, 'prod') }}:
    value: "Terraform Prod"
  ${{ elseif eq(parameters.env, 'test') }}:
    value: "Terraform Test"
  ${{ elseif eq(parameters.env, 'build') }}:
    value: "Terraform Build"
  ${{ else }}:
    value: "Terraform Dev"
- name: agentPool
  value: 'pins-agent-pool-odw-${{ parameters.env }}-uks'
- group: ${{ variables.variableGroupName }}

stages:
- template: stages/run-ado-script-tests.yaml
  parameters:
    agentPool: ${{ variables.agentPool }}
